name: GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deployment:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    environment: production
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    - name: Install
      run: npm ci
    - name: Build and Deploy
      env:
        NODE_ENV: production
        # Remove this line if you would like to skip using google analytics
        REACT_APP_GA_TRACKING_ID: UA-68649021-1
        # This is set automatically by github
        GITHUB_TOKEN: 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
      run: |
          git config user.name "ospitia"
          git config user.email "oscar.espitiamendoza@campus.unimib.it"
          git remote set-url origin https://git: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@github.com/ospitia/ospitia.github.io.git
          npm run deploy